---
title: "Some theory"
author: "Petre Buciu"
---

## Production Matrix

We have at our disposal a huge table recording transaction between industries (the sellers on rows, the buyers on columns). This is how input-output data come from OECD and not also from OECD, but also WIOD, etc. The cells of our table represent monetary sums. We calculate the production matrix, $\textbf{A}$ by using the following matrix formula:

$$\textbf{A} = \textbf{Z}\textbf{x}^{-1}$$ Where $\textbf{Z}$ is the so called transaction table we have been mentioning, $\textbf{x}$ is a diagonal matrix where each diagonal entry represent the invers of the total production ( $x_{i,i}$).

## Leontief inverse matrix

Leontief inverse matrix is $(\textbf{I}-\textbf{A})^{-1}$ being the fundamental tool in input-output analysis. Premultiplying Leontief inverse matrix with $\textbf{f}$ , the final demand, we obtain the a new matrix (or vector, if $\textbf{f}$ is a vector) where we have the total production each sector must produce to satisfy this final demand. We can also write Leontief's inverse as an infinite series:

$$
(\textbf{I}-\textbf{A})^{-1} = \textbf{I} + \textbf{A} + \textbf{A}^2 + ...
$$

## Import content of exports

We can calculate the import content of exports by the following formula:

$$
r = \frac{\textbf{s}^T\textbf{M}(\textbf{I}-\textbf{A})^{-1}\textbf{e}}{\textbf{s}^T\textbf{e}}
$$

Where $\textbf{s}^T$ is the summation vector transposed , $\textbf{M}$ is the import coefficient matrix $\textbf{e}$ is the vector (or matrix if disaggreggated) of exports.

## Domestic Trade Value added 

Similarly, we can calculate the domestic value added content of trade (or more generaly final demand categories) which we will use in our analysis.

$\textbf{VA} = \textbf{v}(\textbf{I}-\textbf{A})^{-1}\textbf{f}$

Where $\textbf{VA}$ is the value added matrix which we cam sum over columns to get the total value added, $\textbf{v}$ is a diagonal matrix with value added coefficients as diagonal entries, and you already know the rest.

## Structural decomposition analysis

We will take a different path from [Baccaro et al (2023](https://www.mpifg.de/994292/baccaro-hadziabdic-operationalisierung-von-wachstumsmodellen)) and rather than calculate induced imports by final demand category and subtracting them from the corresponding category responsible for their existence, by will calculate value added generated by exports and decompose this value added on a year-by-year basis into quantities corresponding to changes in technical coefficients, import coefficients and final demand changes. As recommended by Miller and Blair (2009) we use the average of two polar decomposition.

$\Delta Va=\frac{1}{2}\Delta\textbf{v}(\textbf{L}_1\textbf{f}_1 + \textbf{L}_2\textbf{f}_2) + \frac{1}{2}(\textbf{v}_1\Delta\textbf{L}\textbf{f}_2+\textbf{v}_2\Delta\textbf{L}\textbf{f}_1)+\frac{1}{2}(\textbf{v}_1\textbf{L}_1+\textbf{v}_2\textbf{L}_2)\Delta\textbf{f}$

The difference in the value added generated by final demand categories will be decomposed into three sums, each corresponding to changes in one of its constituent terms.
